include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/flutter_version.dart
    - lib/generated_plugin_registrant.dart

#  strong-mode:
#    implicit-casts: false
#    implicit-dynamic: false

linter:
  rules:
    # from 'flutter_lints', excluded
    use_build_context_synchronously: false # no alternative

    # from 'lints / recommended', excluded
    no_leading_underscores_for_local_identifiers: false # useful for null checked variable variants

    # from 'effective dart', excluded
    avoid_classes_with_only_static_members: false # too strict
    avoid_function_literals_in_foreach_calls: false # benefit?
    lines_longer_than_80_chars: false # nope
    public_member_api_docs: false # this project is not a library

    # from 'effective dart', undecided
    prefer_relative_imports: false # check IDE support (auto import, file move)

    # from 'effective dart', included
    avoid_types_on_closure_parameters: true
    prefer_interpolation_to_compose_strings: true
    unnecessary_lambdas: true

    # from 'pedantic', included
    always_declare_return_types: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    unawaited_futures: true
