# cf guides:
# http://flutter.dev/go/i18n-user-guide
# https://docs.flutter.dev/development/accessibility-and-localization/internationalization

arb-dir: lib/l10n
output-dir: lib/l10ngen
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
preferred-supported-locales:
  - en
synthetic-package: false
