#!/bin/bash
adb shell setprop persist.log.tag.ACodec WARN
adb shell setprop persist.log.tag.AHierarchicalStateMachine ERROR
adb shell setprop persist.log.tag.AudioCapabilities ERROR
adb shell setprop persist.log.tag.AudioTrack INFO
adb shell setprop persist.log.tag.BufferPoolAccessor2.0 INFO
adb shell setprop persist.log.tag.CCodec INFO
adb shell setprop persist.log.tag.CCodecBufferChannel INFO
adb shell setprop persist.log.tag.CCodecBuffers INFO
adb shell setprop persist.log.tag.CCodecConfig INFO
adb shell setprop persist.log.tag.Codec2Client INFO
adb shell setprop persist.log.tag.CompatibilityChangeReporter INFO
adb shell setprop persist.log.tag.ConnectivityManager INFO
adb shell setprop persist.log.tag.Counters WARN
adb shell setprop persist.log.tag.CustomizedTextParser INFO
adb shell setprop persist.log.tag.EGL_emulation INFO
adb shell setprop persist.log.tag.ffmpeg-kit-flutter INFO
adb shell setprop persist.log.tag.HostConnection INFO
adb shell setprop persist.log.tag.InputMethodManager WARN
adb shell setprop persist.log.tag.InsetsSourceConsumer INFO
adb shell setprop persist.log.tag.InputTransport INFO
adb shell setprop persist.log.tag.J4A INFO
adb shell setprop persist.log.tag.MediaCodec WARN
adb shell setprop persist.log.tag.MediaMetadataRetriever INFO
adb shell setprop persist.log.tag.MediaMetadataRetrieverJNI INFO
adb shell setprop persist.log.tag.NativeTiffDecoder INFO
adb shell setprop persist.log.tag.NuMediaExtractor INFO
adb shell setprop persist.log.tag.OpenGLRenderer INFO
adb shell setprop persist.log.tag.PipelineWatcher INFO
adb shell setprop persist.log.tag.ReflectedParamUpdater INFO
adb shell setprop persist.log.tag.skia INFO
adb shell setprop persist.log.tag.SurfaceControl WARN
adb shell setprop persist.log.tag.SurfaceUtils INFO
adb shell setprop persist.log.tag.SurfaceView WARN
adb shell setprop persist.log.tag.VideoCapabilities ERROR

