#!/bin/bash
adb shell setprop log.tag.ACodec WARN
adb shell setprop log.tag.AHierarchicalStateMachine ERROR
adb shell setprop log.tag.AudioCapabilities ERROR
adb shell setprop log.tag.AudioTrack INFO
adb shell setprop log.tag.BufferPoolAccessor2.0 INFO
adb shell setprop log.tag.CCodec INFO
adb shell setprop log.tag.CCodecBufferChannel INFO
adb shell setprop log.tag.CCodecBuffers INFO
adb shell setprop log.tag.CCodecConfig INFO
adb shell setprop log.tag.Codec2Client INFO
adb shell setprop log.tag.CompatibilityChangeReporter INFO
adb shell setprop log.tag.Counters WARN
adb shell setprop log.tag.CustomizedTextParser INFO
adb shell setprop log.tag.EGL_emulation INFO
adb shell setprop log.tag.HostConnection INFO
adb shell setprop log.tag.InputMethodManager WARN
adb shell setprop log.tag.InsetsSourceConsumer INFO
adb shell setprop log.tag.InputTransport INFO
adb shell setprop log.tag.J4A INFO
adb shell setprop log.tag.MediaCodec WARN
adb shell setprop log.tag.MediaMetadataRetriever INFO
adb shell setprop log.tag.MediaMetadataRetrieverJNI INFO
adb shell setprop log.tag.NativeTiffDecoder INFO
adb shell setprop log.tag.NuMediaExtractor INFO
adb shell setprop log.tag.PipelineWatcher INFO
adb shell setprop log.tag.ReflectedParamUpdater INFO
adb shell setprop log.tag.skia INFO
adb shell setprop log.tag.SurfaceControl WARN
adb shell setprop log.tag.SurfaceUtils INFO
adb shell setprop log.tag.SurfaceView WARN
adb shell setprop log.tag.VideoCapabilities ERROR
