name: Release on tag

on:
  push:
    tags:
      - v*

# Declare default permissions as read only.
permissions: read-all

jobs:
  release_github:
    name: GitHub release
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: write
      id-token: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          egress-policy: audit

      # Building relies on the Android Gradle plugin,
      # which requires a modern Java version (not the default one).
      - name: Set up JDK for Android Gradle plugin
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Get Flutter packages
        run: ./flutterw pub get

      - name: Generate app localizations
        run: ./flutterw gen-l10n

      - name: Build signed artifacts
        # `KEY_JKS` should contain the result of:
        # gpg -c --armor keystore.jks
        # `KEY_JKS_PASSPHRASE` should contain the passphrase used for the command above
        run: |
          echo "${{ secrets.KEY_JKS }}" > release.keystore.asc
          gpg -d --passphrase "${{ secrets.KEY_JKS_PASSPHRASE }}" --batch release.keystore.asc > $AVES_STORE_FILE
          rm release.keystore.asc
          mkdir outputs
          scripts/apply_flavor_play.sh
          ./flutterw build appbundle -t lib/main_play.dart --flavor play
          cp build/app/outputs/bundle/playRelease/*.aab outputs
          ./flutterw build apk -t lib/main_play.dart --flavor play
          cp build/app/outputs/apk/play/release/*.apk outputs
          scripts/apply_flavor_izzy.sh
          ./flutterw build apk -t lib/main_izzy.dart --flavor izzy --split-per-abi
          cp build/app/outputs/apk/izzy/release/*.apk outputs
          scripts/apply_flavor_libre.sh
          ./flutterw build appbundle -t lib/main_libre.dart --flavor libre
          cp build/app/outputs/bundle/libreRelease/*.aab outputs
          ./flutterw build apk -t lib/main_libre.dart --flavor libre --split-per-abi
          cp build/app/outputs/apk/libre/release/*.apk outputs
          rm $AVES_STORE_FILE
        env:
          AVES_STORE_FILE: ${{ github.workspace }}/key.jks
          AVES_STORE_PASSWORD: ${{ secrets.AVES_STORE_PASSWORD }}
          AVES_KEY_ALIAS: ${{ secrets.AVES_KEY_ALIAS }}
          AVES_KEY_PASSWORD: ${{ secrets.AVES_KEY_PASSWORD }}
          AVES_GOOGLE_API_KEY: ${{ secrets.AVES_GOOGLE_API_KEY }}

      - name: Generate artifact attestation
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26
        with:
          subject-path: 'outputs/*'

      - name: Create GitHub release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          artifacts: "outputs/*"
          body: "[Changelog](https://github.com/${{ github.repository }}/blob/develop/CHANGELOG.md#${{ github.ref_name }})"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload app bundle
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: appbundle
          path: outputs/app-play-release.aab

  release_play:
    name: Play Store beta release
    needs: [ release_github ]
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Get appbundle from artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: appbundle

      - name: Release to beta channel
        uses: r0adkll/upload-google-play@e738b9dd8f2476ea806d921b64aacd24f34515a5 # v1.1.5
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}
          packageName: deckers.thibault.aves
          releaseFiles: app-play-release.aab
          track: beta
          status: completed
          whatsNewDirectory: whatsnew
